<?php

declare(strict_types=1);

namespace LHcze\BCP47\Enum;

/**
 * Enum for grandfathered language tags from IANA Language Subtag Registry.
 * This file is auto-generated by bin/fetch_iana_registry.php
 * Do not edit manually. Run composer iana:refresh to update.
 */
enum GrandfatheredTag: string
{
    case ART_LOJBAN = 'art-lojban';
    case CEL_GAULISH = 'cel-gaulish';
    case EN_GB_OED = 'en-gb-oed';
    case I_AMI = 'i-ami';
    case I_BNN = 'i-bnn';
    case I_DEFAULT = 'i-default';
    case I_ENOCHIAN = 'i-enochian';
    case I_HAK = 'i-hak';
    case I_KLINGON = 'i-klingon';
    case I_LUX = 'i-lux';
    case I_MINGO = 'i-mingo';
    case I_NAVAJO = 'i-navajo';
    case I_PWN = 'i-pwn';
    case I_TAO = 'i-tao';
    case I_TAY = 'i-tay';
    case I_TSU = 'i-tsu';
    case NO_BOK = 'no-bok';
    case NO_NYN = 'no-nyn';
    case SGN_BE_FR = 'sgn-be-fr';
    case SGN_BE_NL = 'sgn-be-nl';
    case SGN_CH_DE = 'sgn-ch-de';
    case ZH_GUOYU = 'zh-guoyu';
    case ZH_HAKKA = 'zh-hakka';
    case ZH_MIN = 'zh-min';
    case ZH_MIN_NAN = 'zh-min-nan';
    case ZH_XIANG = 'zh-xiang';
}
